image: node:18

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
    - cp -r build/* public/
  artifacts:
    paths:
      - public
  only:
    - main 